name: Website build and deploy

on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  # 打包及上传Artifact
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # 将代码拉到虚拟机
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Use Node.js # 安装Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install and Build # 下载依赖 打包项目
        run: |
          npm install
          npm run docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs/.vuepress/dist
  # Deployment Github Page
  # deploy:
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v2
